project_name          = "arxplorer"
environment           = "dev"
storage_bucket_prefix = "arxplorer-dev"
db_instance_class     = "db.t3.micro"
db_name               = "arxplorer_dev"
instance_type         = "t3.micro"
min_size              = 1
max_size              = 2
vpc_cidr              = "10.0.0.0/16"
availability_zones    = ["ca-central-1a", "ca-central-1b"]
